# services config in one docker-compose file for integrate test
services:
  zookeeper:
    image: zookeeper:3.9.4
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks: [itnet]

  nacos:
    image: nacos/nacos-server:v2.5.2
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8848/nacos/v1/console/health/liveness" ]
      interval: 7s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks: [itnet]

  polaris:
    image: polarismesh/polaris-standalone:v1.17.2
    privileged: true
    ports:
      - "8090:8090"
      - "8091:8091"
      - "8093:8093"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8090/" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks: [itnet]

  etcd:
    image: quay.io/coreos/etcd:v3.4.28
    environment:
      ETCDCTL_API: "3"
    command:
      - etcd
      - --name=etcd0
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd:2380
      - --initial-cluster=etcd0=http://etcd:2380
      - --initial-cluster-state=new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data
    healthcheck:
      test: [ "CMD", "etcdctl", "--endpoints=http://localhost:2379", "endpoint", "health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks: [itnet]

networks:
  itnet:
    name: itnet

volumes:
  etcd-data:
