version: '3.5'

services:
  zk:
    image: zookeeper
    container_name: zk
    networks:
      - dubbo
    ports:
      - 2181:2181
#  nacos:
#    image: nacos/nacos-server:1.4.1
#    container_name: nacos-standalone
#    networks:
#      - dubbo
#    environment:
#      - PREFER_HOST_MODE=hostname
#      - MODE=standalone
#    ports:
#      - "8848:8848"
#    healthcheck:
#      test: "curl --fail http://127.0.0.1:8848/nacos/v1/console/health/liveness || exit 1"
#      interval: 5s

# 网络
networks:
  dubbo:
    name: dubbo-go-samples
    driver: bridge