version: "3"
services:
  go-client:
    container_name: go-client
    build:
      context: ../shopping-order
      dockerfile: ./Dockerfile
      args:
        - APP=go-client
    environment:
      - APP=go-client
      - CONF_CONSUMER_FILE_PATH=/build/go-client/conf/client.yml
      - APP_LOG_CONF_FILE=/build/go-client/conf/log.yml
      - SEATA_CONF_FILE=/build/go-client/conf/seata.yml
    depends_on:
      - nacos
      - go-server-product
      - go-server-order

  go-server-order:
    container_name: go-server-order
    build:
      context: ../shopping-order
      dockerfile: ./Dockerfile
      args:
        - APP=go-server-order
    environment:
      - APP=go-server-order
      - CONF_PROVIDER_FILE_PATH=/build/go-server-order/conf/server.yml
      - APP_LOG_CONF_FILE=/build/go-server-order/conf/log.yml
      - SEATA_CONF_FILE=/build/go-server-order/conf/seata.yml
    depends_on:
      - nacos
      - mysql
      - seata
    ports:
      - "20000:20000"

  go-server-product:
    container_name: go-server-product
    build:
      context: ../shopping-order
      dockerfile: ./Dockerfile
      args:
        - APP=go-server-product
    environment:
      - APP=go-server-product
      - CONF_PROVIDER_FILE_PATH=/build/go-server-product/conf/server.yml
      - APP_LOG_CONF_FILE=/build/go-server-product/conf/log.yml
      - SEATA_CONF_FILE=/build/go-server-product/conf/seata.yml
    depends_on:
      - nacos
      - mysql
      - seata
    ports:
      - "20001:20001"

  seata:
    container_name: seata
    image: seataio/seata-server
    ports:
      - "8091:8091"
    volumes:
      - ./seata/registry.conf:/seata-server/resources/registry.conf
      - ./seata/file.conf:/seata-server/resources/file.conf
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=db
    depends_on:
      - nacos
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "3306:3306"

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: on-failure

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./logs:/home/nacos/logs
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./logs:/var/log/grafana
    ports:
      - 3000:3000
