# dubbo router yaml configure file
routerRules:
  - scope: application
    force: true
    runtime: false
    enabled: true
    valid: true
    priority: 1
    key: demo-provider
    tags:
      - name: beijing
        addresses: [192.168.1.1, 1.2.3.4]
      - name: shenzhen
        addresses: [192.168.1.3, 192.168.1.4]